# This file should not be checked into Git. It's published only for demonstration purpose.
secretGenerator:
- name: mysql-root-pass
  literals:
  - password=R00t
- name: mysql-user
  literals:
  - username=callicoder 
- name: mysql-pass
  literals:
  - password=c@ll1c0d3r
- name: mysql-db
  literals:
  - database=polls      
- name: mysql-url
  literals:
  - url=jdbc:mysql://polling-app-mysql:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
resources:
  - mysql-deployment.yaml
  - polling-app-server.yaml  